// waveformFilter.js
//
// A JavaScript port of the backend's waveform filtering, so a client can
// ask for unfiltered samples and do this itself.
//
// Why bother: the backend sends integer counts when it does not filter,
// and integers both serialise compactly and delta-encode well.  Filtering
// server-side turns them into fractional doubles that JSON writes as long
// scientific-notation strings.  Measured on a six-channel event, 73,649
// samples: server-filtered and quantized is 135 KB gzipped, while
// unfiltered with delta encoding is 92 KB - 32% smaller AND lossless,
// because nothing is quantized.  So filtering here is not only cheap, it
// makes the payload smaller.
//
// Request the samples with:  ?filter=false&enableDeltaEncoding=true
//
// The coefficients are a third-order Butterworth bandpass as second-order
// sections, generated by scipy in testing/data/signalProcessing/design.py
// and copied verbatim from src/signalProcessing/bandpass.cpp.  Verified
// against the same reference impulse responses the C++ is tested with:
// every sampling rate reproduces scipy sample-for-sample to 0.0.
//
// The passbands are 0.5 Hz to just under Nyquist, per design.py.

const DESIGNS = {
  40: {
    tolerance: 1.e-4,
    b: [
      [0.6734790477138246, 1.3469580954276492, 0.6734790477138246],
      [1.0, 0.0, -1.0],
      [1.0, -2.0, 1.0]
    ],
    a: [
      [1.0, 1.6484753179477056, 0.7338442895664062],
      [1.0, -0.19991468011753089, -0.6681786379192985],
      [1.0, -1.918993448174642, 0.9249638747061851]
    ]
  },
  80: {
    tolerance: 1.e-4,
    b: [
      [0.8214636347864291, 1.6429272695728583, 0.8214636347864291],
      [1.0, 0.0, -1.0],
      [1.0, -2.0, 1.0]
    ],
    a: [
      [1.0, 1.8322493755567273, 0.8551240027931296],
      [1.0, -0.107703445133422, -0.8206787908286602],
      [1.0, -1.9600400538405367, 0.9615546705021153]
    ]
  },
  100: {
    tolerance: 1.e-3,
    b: [
      [0.7065679722682777, 1.4131359445365554, 0.7065679722682777],
      [1.0, 0.0, -1.0],
      [1.0, -2.0, 1.0]
    ],
    a: [
      [1.0, 1.647913599700461, 0.7329342638536966],
      [1.0, -0.24355497400690285, -0.7028117712403572],
      [1.0, -1.9681772087145875, 0.9691512708948594]
    ]
  },
  200: {
    tolerance: 1.e-3,
    b: [
      [0.717921056028987, 1.435842112057974, 0.717921056028987],
      [1.0, 0.0, -1.0],
      [1.0, -2.0, 1.0]
    ],
    a: [
      [1.0, 1.6477316110123414, 0.7326354764117732],
      [1.0, -0.2584223068197652, -0.7146105533645492],
      [1.0, -1.9841892720072534, 0.9844343905181866]
    ]
  },
  500: {
    tolerance: 2.e-3,
    b: [
      [0.7723380978421511, 1.5446761956843023, 0.7723380978421511],
      [1.0, 0.0, -1.0],
      [1.0, -2.0, 1.0]
    ],
    a: [
      [1.0, 1.7229839217145448, 0.7788929286543191],
      [1.0, -0.21821025731826826, -0.7706599046098872],
      [1.0, -1.9936996438745507, 0.9937390141821811]
    ]
  },
  1000: {
    tolerance: 1.e-2,
    b: [
      [0.5258784146071691, 1.0517568292143382, 0.5258784146071691],
      [1.0, 0.0, -1.0],
      [1.0, -2.0, 1.0]
    ],
    a: [
      [1.0, 1.2505393112081853, 0.5459198908866272],
      [1.0, -0.48771304484689926, -0.5075484297228321],
      [1.0, -1.9968550812497046, 0.9968649403993294]
    ]
  }};

/**
 * Picks the design for an observed sampling rate.
 *
 * Packet sampling rates are slightly off the nominal value, so a rate
 * close to a design gets that design.  A rate that is NOT close is
 * REFUSED rather than snapped to the nearest: applying a filter whose
 * corners sit in the wrong place produces a trace that looks entirely
 * plausible and is wrong, which is worse than not filtering.  Keep this
 * strict - the C++ is.
 *
 * @param {number} samplingRate Hz, as the segment reports it.
 * @returns {number|null} the design's nominal rate, or null if there is none.
 */
export function getValidSamplingRate(samplingRate) {
  if (!(samplingRate > 0)) { return null; }
  for (const [nominal, design] of Object.entries(DESIGNS)) {
    if (Math.abs(samplingRate - Number(nominal)) < design.tolerance) {
      return Number(nominal);
    }
  }
  return null;
}

/**
 * Removes the mean.
 *
 * @param {ArrayLike<number>} x
 * @returns {Float64Array} a new array; the input is not modified.
 */
export function demean(x) {
  const n = x.length;
  if (n === 0) { return new Float64Array(0); }
  let sum = 0;
  for (let i = 0; i < n; ++i) { sum += x[i]; }
  const mean = sum/n;
  const y = new Float64Array(n);
  for (let i = 0; i < n; ++i) { y[i] = x[i] - mean; }
  return y;
}

/**
 * Removes a best-fit straight line.
 *
 * A generalisation of demean: with no trend the slope comes out at zero and
 * this reduces to subtracting the mean.  Worth doing before the bandpass
 * because a trend is a large low-frequency component, and the filter's
 * response to it is a long excursion at the START of the record - the samples
 * where an analyst is looking for the first arrival.
 *
 * Ported from the backend's C++ (RTSeis).  The regressor is the sample INDEX,
 * evenly spaced from zero, so its mean and variance have closed forms and
 * neither has to be accumulated:
 *
 *   mean(i) = (n-1)/2                     Gauss's formula, simplified
 *   var(i)  = (n-1)(2n-1)/6 - mean(i)^2   sum of consecutive squares
 *
 * and the covariance follows from expanding (i - mean(i))(x_i - mean(x)) and
 * cancelling, which leaves one pass over the data instead of two.
 *
 * @param {ArrayLike<number>} x
 * @returns {Float64Array} a new array; the input is not modified.
 */
export function detrend(x) {
  const n = x.length;
  // A single sample has no line to fit; demeaning it is the sensible limit,
  // and the C++ throws here only because it has no such caller.
  if (n < 2) { return demean(x); }
  const meanIndex = 0.5*(n - 1);
  const varIndex = (n - 1)*(2*(n - 1) + 1)/6. - meanIndex*meanIndex;
  let sum = 0;
  let sumIndexX = 0;
  for (let i = 0; i < n; ++i) {
    sum = sum + x[i];
    sumIndexX = sumIndexX + i*x[i];
  }
  const mean = sum/n;
  const covariance = (sumIndexX/n) - meanIndex*mean;
  const slope = varIndex > 0 ? covariance/varIndex : 0;
  const intercept = mean - slope*meanIndex;
  const y = new Float64Array(n);
  for (let i = 0; i < n; ++i) {
    y[i] = x[i] - (intercept + i*slope);
  }
  return y;
}

/**
 * Applies a cascade of second-order sections.
 *
 * Transposed direct form II, the same recurrence scipy's sosfilt uses.
 * a[s][0] is 1 for every section and is therefore not read.
 *
 * @param {number[][]} b numerator coefficients, one row per section
 * @param {number[][]} a denominator coefficients, one row per section
 * @param {ArrayLike<number>} x
 * @param {number[][]|null} [zi] initial state per section, as returned by
 *   `sosfiltZi` and already scaled.  Omit for zero state, which is what the
 *   C++ reference uses.
 * @returns {Float64Array}
 */
export function sosfilt(b, a, x, zi = null) {
  const y = Float64Array.from(x);
  for (let s = 0; s < b.length; ++s) {
    const b0 = b[s][0], b1 = b[s][1], b2 = b[s][2];
    const a1 = a[s][1], a2 = a[s][2];
    let z1 = zi === null ? 0 : zi[s][0];
    let z2 = zi === null ? 0 : zi[s][1];
    for (let i = 0; i < y.length; ++i) {
      const v = y[i];
      const o = b0*v + z1;
      z1 = b1*v - a1*o + z2;
      z2 = b2*v - a2*o;
      y[i] = o;
    }
  }
  return y;
}

/**
 * Steady-state initial conditions for a cascade, scipy's `sosfilt_zi`.
 *
 * Starting the filter from zero state asserts that the signal was zero for
 * all time before the first sample.  It was not, so the filter answers the
 * implied step at sample 0 with a transient - which lands on the first
 * seconds of the record, where the first arrival is.  Starting from the state
 * the filter WOULD be in, had it been running on a constant equal to the
 * first sample, removes that step.
 *
 * Per section, this is scipy's `lfilter_zi`, whose 2x2 solve has a closed
 * form for a biquad:
 *
 *   (1 + a1) z0 - z1 = b1 - a1 b0
 *        a2  z0 + z1 = b2 - a2 b0
 *
 * and each section is scaled by the DC gain of the ones before it, since that
 * is what a constant reaching it has been multiplied by.  For a BANDPASS that
 * scale hits zero at the first section with a zero at DC - correctly, because
 * a constant is annihilated there and every later section sees nothing.
 *
 * @param {number[][]} b numerator coefficients, one row per section
 * @param {number[][]} a denominator coefficients, one row per section
 * @returns {number[][]} initial state per section, for a unit first sample
 */
export function sosfiltZi(b, a) {
  const zi = [];
  let scale = 1;
  for (let s = 0; s < b.length; ++s) {
    const b0 = b[s][0], b1 = b[s][1], b2 = b[s][2];
    const a1 = a[s][1], a2 = a[s][2];
    const rhs0 = b1 - a1*b0;
    const rhs1 = b2 - a2*b0;
    const denominator = 1 + a1 + a2;
    const z0 = denominator !== 0 ? (rhs0 + rhs1)/denominator : 0;
    const z1 = rhs1 - a2*z0;
    zi.push([scale*z0, scale*z1]);
    scale = denominator !== 0 ? scale*(b0 + b1 + b2)/denominator : 0;
  }
  return zi;
}

/**
 * Bandpass filters one segment's samples.
 *
 * Starts from the steady state for the first sample rather than from zero.
 * With a detrended input the first sample is usually small and the two agree,
 * but on anything that starts away from zero the difference is a visible
 * excursion across the opening seconds.
 *
 * NOTE this is where the port stops matching a bare `scipy.signal.sosfilt`.
 * It now reproduces `sosfilt(sos, x, zi=sosfilt_zi(sos)*x[0])`, which is just
 * as standard and just as testable - but the C++ starts from zero state, so
 * the two no longer agree over the first second or so of a record.
 *
 * @param {ArrayLike<number>} samples
 * @param {number} samplingRate Hz
 * @param {boolean} [steadyState] false to start from zero state, which is what
 *   the C++ reference does.
 * @returns {Float64Array}
 * @throws {Error} if there is no design for this sampling rate.
 */
export function bandpassFilter(samples, samplingRate, steadyState = true) {
  const nominal = getValidSamplingRate(samplingRate);
  if (nominal === null) {
    throw new Error(`No bandpass design for a sampling rate of ${samplingRate} Hz`);
  }
  const design = DESIGNS[nominal];
  if (!steadyState || samples.length === 0) {
    return sosfilt(design.b, design.a, samples);
  }
  const first = samples[0];
  const zi = sosfiltZi(design.b, design.a).map((section) => [
    section[0]*first,
    section[1]*first,
  ]);
  return sosfilt(design.b, design.a, samples, zi);
}

/**
 * Detrends then bandpass filters one segment, in place on a copy.
 *
 * Detrend rather than demean: a record that starts on a ramp - a settling
 * instrument, a slipping baseline - leaves the bandpass ringing through the
 * first seconds, which is exactly where the first arrival is.  With no trend
 * present the two are the same operation.
 *
 * A segment that cannot be filtered comes back AS IT WENT IN, with
 * `filtered: false`, rather than throwing.  That mirrors the backend: an
 * unfiltered trace is honest, a wrongly-filtered one is not, and losing
 * the whole record section because one channel runs at an odd rate would
 * be worse than either.
 *
 * @param {{data: ArrayLike<number>, samplingRate: number}} segment
 * @returns {{data: Float64Array, samplingRate: number, filtered: boolean}}
 */
export function filterSegment(segment) {
  try {
    const filtered = bandpassFilter(detrend(segment.data), segment.samplingRate);
    return { ...segment, data: filtered, filtered: true };
  } catch (error) {
    return { ...segment, data: Float64Array.from(segment.data), filtered: false };
  }
}

/**
 * Decodes a segment as the backend sends it, then filters it.
 *
 * Undo the differences if `deltaEncoded`, then divide by `gain`.  With
 * both encoding options off that is a no-op - gain is 1 and deltaEncoded
 * is false - so this one path handles every reply.
 *
 * Filtering PER SEGMENT is deliberate.  Segments are separated by real
 * gaps in the record, so filtering across a join would ring the filter
 * against a discontinuity that is not in the ground motion.
 *
 * @param {{data: number[], gain: number, deltaEncoded: boolean, samplingRate: number}} segment
 * @returns {{data: Float64Array, samplingRate: number, filtered: boolean}}
 */
export function decodeAndFilterSegment(segment) {
  const n = segment.data.length;
  const decoded = new Float64Array(n);
  const gain = segment.gain ?? 1;
  let running = 0;
  for (let i = 0; i < n; ++i) {
    running = segment.deltaEncoded ? running + segment.data[i] : segment.data[i];
    decoded[i] = running/gain;
  }
  return filterSegment({ ...segment, data: decoded });
}
